### ISSUE TITLE
Material types ja Locations -fasetit eivät käänny

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha#1542]
### Mikä vikana?

Koha-Suomen oma Material types -fasetti ja yhteisöstä tuleva Locations-fasetti eivät käänny hakutulosnäytöllä:

![kuva](https://github.com/user-attachments/assets/74ad40a3-492e-4c6a-ac15-6cefc17fafc4)

Kuvaukset tulevat Hakukoneen asetuksista Hakukentät-välilehden Otsikko-sarakkeesta:

![kuva](https://github.com/user-attachments/assets/903cb299-0001-4e0c-974d-41d67cd839bf)

Koha-Suomen staff-prog-käännöstiedostossa ei ole kuitenkaan mukana Material types -termiä. Locations sieltä löytyy ja sille on merkitty käyttöpaikaksikin facets.inc, mutta se ei siltikään käänny.

**Comment by johannaraisa** [comment]
Locations korjattu mäppäystiedostoon. "Material types" vaatii selvittelyä, se tulee kannasta ja todennäköisesti ei sen takia nappaa käännökseen.

**Comment by johannaraisa** [comment]
![image](https://github.com/user-attachments/assets/c98bd2fd-0621-4528-a195-c010afed96d8)
Käännöstiedostot eivät pure noihin omiin fasetteihin, niille voi vaihtaa otsikko-arvoa, jolloin se muuttuu myös haussa. Nuo ennalta määritetyt löytyvät facet.inc tiedostosta ja ne voi kääntää käännöstiedostoilla.

**Comment by johannaraisa** [comment]
Taisin keksiä, miten nuo saa käännettyä ilman koodimuutoksia. 
![image](https://github.com/user-attachments/assets/e4ac7354-8125-4c86-ac8c-8ca37c57481e)
Tekee noista kieliversiot ja sitten hakunäytöllä näyttää käytetyn kielen version.

**Comment by johannaraisa** [comment]
Lisäsin nuo säännöt testimäppäykseen ja päivitin ne Lumpeissa. Kaikki kolme tuli hakunäytölle näkyviin, säädin intranetusercss-asetusta seuraavasti.

```css
#mtype_id, #mtype_sv_id, #mtype_fi_id {
  display:none;
}

:lang("fi-FI") > #mtype_fi_id {
  display:block !important;
}

:lang("sv-SE") > #mtype_sv_id {
  display:block !important;
}

:lang("en") > #mtype_id {
  display:block !important;
}
```
